---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: layerhubmongo
  labels:
    app: layerhubmongo
spec:
  serviceName: "layerhubmongo"
  replicas: 1
  selector:
    matchLabels:
      app: layerhubmongo
  template:
    metadata:
      labels:
        app: layerhubmongo
    spec:
      containers:
        - name: layerhubmongo
          image: docker.io/library/mongo:8.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 27017
          envFrom:
            - configMapRef:
                name: layerhubmongo-env
          volumeMounts:
            - name: apphost-feed4158f1-layerhubmongo-data
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: apphost-feed4158f1-layerhubmongo-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
