services:
  layerhubpostgresql:
    image: "docker.io/library/postgres:17.4"
    environment:
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256"
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
      POSTGRES_USER: "${USERNAME}"
      POSTGRES_PASSWORD: "${PASSWORD}"
    ports:
      - "5433:5432"
    volumes:
      - type: "volume"
        target: "/var/lib/postgresql/data"
        source: "apphost-feed4158f1-LayerHubPostgreSql-data"
        read_only: false
    networks:
      - "aspire"
  layerhubmongo:
    image: "docker.io/library/mongo:8.0"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "admin"
      MONGO_INITDB_ROOT_PASSWORD: "${LAYERHUBMONGO_PASSWORD}"
    ports:
      - "8000:27017"
    volumes:
      - type: "volume"
        target: "/data/db"
        source: "apphost-feed4158f1-LayerHubMongo-data"
        read_only: false
    networks:
      - "aspire"
  api:
    image: "${API_IMAGE}"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "8001"
      ConnectionStrings__MongoDbConnection: "mongodb://admin:${LAYERHUBMONGO_PASSWORD}@LayerHubMongo:27017/LayerHubReadDb?authSource=admin&authMechanism=SCRAM-SHA-256"
      ConnectionStrings__DefaultConnection: "Host=LayerHubPostgreSql;Port=5432;Username=${USERNAME};Password=${PASSWORD};Database=LayerHubWriteDb"
    ports:
      - "8002:8001"
      - "8004:8003"
    depends_on:
      layerhubmongo:
        condition: "service_started"
      layerhubpostgresql:
        condition: "service_started"
    networks:
      - "aspire"
  web:
    image: "${WEB_IMAGE}"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "8005"
      services__Api__http__0: "http://Api:8001"
    ports:
      - "8006:8005"
      - "8008:8007"
    networks:
      - "aspire"
networks:
  aspire:
    driver: "bridge"
volumes:
  apphost-feed4158f1-LayerHubPostgreSql-data:
    driver: "local"
  apphost-feed4158f1-LayerHubMongo-data:
    driver: "local"
